import type { LifeStage } from '@/domain/gyeol/types';

export const copy = {
  common: {
    loading: '불러오는 중',
    retry: '다시 시도',
    add: '추가',
    complete: '완료',
    cancel: '취소',
    delete: '삭제',
    save: '저장',
    confirm: '확인',
  },
  db: {
    loading: '불러오는 중',
    errorTitle: '연결 오류',
    errorDefault: '데이터를 불러오지 못했습니다',
  },
  onboarding: {
    welcomeTitle: '솜알이 왔어요',
    welcomeBody: '할 일을 완료하면 솜몽이 자라요',
    welcomeCta: '시작하기',
    plantTitle: '첫 할 일을 적어주세요',
    plantPlaceholder: '할 일',
    plantCta: '심기',
    completeCta: '완료하기',
    hatchTitle: '솜몽이 깨어났어요',
    hatchCta: '오늘 화면으로',
  },
  today: {
    emptyTitle: '할 일을 추가해 보세요',
    emptyCta: '씨앗 심기',
    sectionTodos: '오늘의 씨앗',
    sectionCompleted: (n: number) => `완료 ${n}`,
    emptyTodos: '할 일이 없습니다',
    fab: '+ 씨앗 심기',
    petWaiting: '오늘의 씨앗을 기다리는 중',
    petHatched: '솜몽이 깨어났어요',
    loadError: '목록을 불러오지 못했습니다. 다시 시도해 주세요.',
    addError: '추가하지 못했습니다. 다시 시도해 주세요.',
    completeError: '완료를 저장하지 못했습니다. 다시 시도해 주세요.',
    alreadyCompleted: '이미 완료된 항목입니다',
    coreSeedLimit: '핵심 씨앗은 하루 3개까지입니다',
    mistSection: '안개 씨앗',
    mistHint: '어제 미완료 — 오늘 다시 밝혀보세요',
    dailyCapReached: '오늘 결이 가득 찼어요',
    deleted: '삭제했습니다',
    updated: '수정했습니다',
    uncompleted: '완료를 취소했습니다',
    rescheduled: '오늘로 옮겼습니다',
  },
  todoInput: {
    title: '씨앗 심기',
    placeholder: '할 일',
    categoryLabel: '카테고리',
    categoryPlaceholder: '카테고리 이름',
    newCategory: '+ 새 카테고리',
    createCategory: '카테고리 만들기',
    coreSeed: '핵심 씨앗',
    coreSeedHint: '최대 3개',
    submit: '심기',
  },
  coreSeed: {
    title: '핵심 씨앗',
    slotLabel: '씨앗',
    rank: (n: number) => `${n}`,
  },
  todoItem: {
    complete: '완료',
    completed: '완료됨',
    coreSeedOn: '★ 핵심 씨앗',
    coreSeedOff: '핵심 씨앗 지정',
    swipeComplete: '완료',
    swipeDelete: '삭제',
    tapDetail: '상세 보기',
  },
  todoDetail: {
    title: '할 일',
    editTitle: '제목',
    deleteConfirm: '이 할 일을 삭제할까요?',
    uncomplete: '완료 취소',
    reschedule: '오늘로 옮기기',
    archive: '보관',
    save: '저장',
    delete: '삭제',
    mistNote: '안개 씨앗 — 오늘로 옮기거나 완료하세요',
  },
  petRoom: {
    title: '펫방',
    talk: '말 걸기',
    evolve: '진화하기',
    evolving: '진화 중',
    todayGyeol: '오늘의 결',
    noGyeol: '오늘 쌓인 결이 없습니다',
    loadError: '펫방을 불러오지 못했습니다. 다시 시도해 주세요.',
  },
  archive: {
    title: '기록의 방',
    subtitle: '지나간 여정',
    emptyTitle: '보관된 여정이 없습니다',
    emptyMessage: '성장한 펫의 기록이 여기에 남습니다',
    currentJourney: '현재 여정',
    evolutionHistory: '진화 기록',
    pastJourneys: '이전 여정',
    newJourney: '새 여정 시작',
    newJourneyFree: '새 여정 시작',
    newJourneyBlocked: '성장기 진화 후 새 여정을 시작할 수 있습니다',
    newJourneyConfirm: '현재 펫은 기록에 보관되고 새 솜알이 시작됩니다',
    weeklyTitle: '이번 주 결',
    weeklyEmpty: '이번 주 기록이 없습니다',
    loadError: '기록을 불러오지 못했습니다',
    startJourneyError: '새 여정을 시작하지 못했습니다',
  },
  store: {
    title: '상점',
    subtitle: '곧 열립니다',
    comingSoon: '준비 중',
    items: '펫 · 방 · 소품',
    note: '핵심 진화와 기본 여정은 무료입니다',
  },
  settings: {
    title: '설정',
    subtitle: '앱과 데이터',
    notifications: '아침 알림',
    notificationsHint: '매일 9시 핵심 씨앗 알림',
    categories: '카테고리',
    categoriesHint: '삭제 시 할 일은 다른 카테고리로 옮겨집니다',
    deleteCategory: '삭제',
    deleteCategoryConfirm: (name: string) => `「${name}」을 삭제할까요?`,
    lastCategory: '카테고리는 1개 이상 필요합니다',
    resetData: '데이터 초기화',
    resetHint: '모든 할 일·펫·기록이 삭제됩니다',
    resetConfirm: '정말 초기화할까요? 되돌릴 수 없습니다',
    resetDone: '초기화했습니다',
    version: 'TodoSom',
  },
  evolution: {
    title: '성장 진행',
    completions: (n: number, max: number) => `완료 ${n}/${max}`,
    points: (n: number, max: number) => `결 ${n}/${max}`,
    days: (n: number, max: number) => `함께한 날 ${n}/${max}`,
    ready: '진화 조건 충족',
    done: '성장기 진화 완료',
    hint: '완료·결·함께한 날 중 하나 충족',
  },
  notifications: {
    title: '오늘의 씨앗',
    body: '오늘 가장 중요한 일 하나, 함께 해볼까요?',
  },
} as const;

const LIFE_STAGE_LABELS: Record<LifeStage, string> = {
  egg: '솜알',
  baby: '유년기',
  growth: '성장기',
  mature: '성숙기',
  archived: '보관됨',
};

export function formatLifeStage(stage: LifeStage | string): string {
  return LIFE_STAGE_LABELS[stage as LifeStage] ?? stage;
}

export function formatPetRoomSubtitle(name: string, stage: LifeStage | string): string {
  return `${name} · ${formatLifeStage(stage)}`;
}
